// <auto-generated />
using System;
using Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infra.Data.Migrations
{
    [DbContext(typeof(EFContext))]
    [Migration("20210102194110_v5")]
    partial class v5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("CaixaEletronicaSaque", b =>
                {
                    b.Property<int>("CaixaEletronicaId")
                        .HasColumnType("int");

                    b.Property<int>("SaqueId")
                        .HasColumnType("int");

                    b.HasKey("CaixaEletronicaId", "SaqueId");

                    b.HasIndex("SaqueId");

                    b.ToTable("CaixaEletronicaSaque");
                });

            modelBuilder.Entity("Domain.Entidades.CaixaEletronica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Datetime");

                    b.Property<int>("NotasId")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeNotas")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("NotasId");

                    b.ToTable("CaixaEletronica");
                });

            modelBuilder.Entity("Domain.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoClienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoClienteId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Domain.Entidades.Notas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<decimal>("ValorNota")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Notas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataCadastro = new DateTime(2021, 1, 2, 16, 41, 8, 0, DateTimeKind.Unspecified),
                            Disponivel = true,
                            ValorNota = 5m
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataCadastro = new DateTime(2021, 1, 2, 16, 41, 8, 0, DateTimeKind.Unspecified),
                            Disponivel = true,
                            ValorNota = 10m
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataCadastro = new DateTime(2021, 1, 2, 16, 41, 8, 0, DateTimeKind.Unspecified),
                            Disponivel = true,
                            ValorNota = 20m
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataCadastro = new DateTime(2021, 1, 2, 16, 41, 8, 0, DateTimeKind.Unspecified),
                            Disponivel = true,
                            ValorNota = 50m
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataCadastro = new DateTime(2021, 1, 2, 16, 41, 8, 0, DateTimeKind.Unspecified),
                            Disponivel = true,
                            ValorNota = 100m
                        });
                });

            modelBuilder.Entity("Domain.Entidades.NotasSugerida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int>("NotasId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorNotaSugerida")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NotasId");

                    b.ToTable("NotasSugerida");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataCadastro = new DateTime(2021, 1, 2, 16, 41, 8, 984, DateTimeKind.Local).AddTicks(7536),
                            NotasId = 1,
                            ValorNotaSugerida = 5m
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataCadastro = new DateTime(2021, 1, 2, 16, 41, 8, 985, DateTimeKind.Local).AddTicks(318),
                            NotasId = 2,
                            ValorNotaSugerida = 5m
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataCadastro = new DateTime(2021, 1, 2, 16, 41, 8, 985, DateTimeKind.Local).AddTicks(330),
                            NotasId = 2,
                            ValorNotaSugerida = 10m
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataCadastro = new DateTime(2021, 1, 2, 16, 41, 8, 985, DateTimeKind.Local).AddTicks(333),
                            NotasId = 3,
                            ValorNotaSugerida = 5m
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataCadastro = new DateTime(2021, 1, 2, 16, 41, 8, 985, DateTimeKind.Local).AddTicks(336),
                            NotasId = 3,
                            ValorNotaSugerida = 10m
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            DataCadastro = new DateTime(2021, 1, 2, 16, 41, 8, 985, DateTimeKind.Local).AddTicks(339),
                            NotasId = 3,
                            ValorNotaSugerida = 20m
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            DataCadastro = new DateTime(2021, 1, 2, 16, 41, 8, 985, DateTimeKind.Local).AddTicks(341),
                            NotasId = 4,
                            ValorNotaSugerida = 5m
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            DataCadastro = new DateTime(2021, 1, 2, 16, 41, 8, 985, DateTimeKind.Local).AddTicks(344),
                            NotasId = 4,
                            ValorNotaSugerida = 10m
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            DataCadastro = new DateTime(2021, 1, 2, 16, 41, 8, 985, DateTimeKind.Local).AddTicks(348),
                            NotasId = 4,
                            ValorNotaSugerida = 20m
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            DataCadastro = new DateTime(2021, 1, 2, 16, 41, 8, 985, DateTimeKind.Local).AddTicks(350),
                            NotasId = 4,
                            ValorNotaSugerida = 50m
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            DataCadastro = new DateTime(2021, 1, 2, 16, 41, 8, 985, DateTimeKind.Local).AddTicks(353),
                            NotasId = 5,
                            ValorNotaSugerida = 5m
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            DataCadastro = new DateTime(2021, 1, 2, 16, 41, 8, 985, DateTimeKind.Local).AddTicks(355),
                            NotasId = 5,
                            ValorNotaSugerida = 10m
                        },
                        new
                        {
                            Id = 13,
                            Ativo = true,
                            DataCadastro = new DateTime(2021, 1, 2, 16, 41, 8, 985, DateTimeKind.Local).AddTicks(357),
                            NotasId = 5,
                            ValorNotaSugerida = 20m
                        },
                        new
                        {
                            Id = 14,
                            Ativo = true,
                            DataCadastro = new DateTime(2021, 1, 2, 16, 41, 8, 985, DateTimeKind.Local).AddTicks(360),
                            NotasId = 5,
                            ValorNotaSugerida = 50m
                        },
                        new
                        {
                            Id = 15,
                            Ativo = true,
                            DataCadastro = new DateTime(2021, 1, 2, 16, 41, 8, 985, DateTimeKind.Local).AddTicks(363),
                            NotasId = 5,
                            ValorNotaSugerida = 100m
                        });
                });

            modelBuilder.Entity("Domain.Entidades.Saque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("CodigoSaque")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Datetime");

                    b.Property<DateTime>("DataSaque")
                        .HasColumnType("Datetime");

                    b.HasKey("Id");

                    b.ToTable("Saque");
                });

            modelBuilder.Entity("Domain.Entidades.TipoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigla")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoCliente");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataCadastro = new DateTime(2021, 1, 2, 16, 41, 8, 0, DateTimeKind.Unspecified),
                            Nome = "Pessoa Fisica",
                            Sigla = "PF"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataCadastro = new DateTime(2021, 1, 2, 16, 41, 8, 0, DateTimeKind.Unspecified),
                            Nome = "Pessoa Juridica",
                            Sigla = "PJ"
                        });
                });

            modelBuilder.Entity("CaixaEletronicaSaque", b =>
                {
                    b.HasOne("Domain.Entidades.CaixaEletronica", null)
                        .WithMany()
                        .HasForeignKey("CaixaEletronicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Saque", null)
                        .WithMany()
                        .HasForeignKey("SaqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entidades.CaixaEletronica", b =>
                {
                    b.HasOne("Domain.Entidades.Cliente", "Cliente")
                        .WithMany("CaixaEletronica")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entidades.Notas", "Notas")
                        .WithMany("CaixaEletronicas")
                        .HasForeignKey("NotasId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Notas");
                });

            modelBuilder.Entity("Domain.Entidades.Cliente", b =>
                {
                    b.HasOne("Domain.Entidades.TipoCliente", "TipoCliente")
                        .WithMany()
                        .HasForeignKey("TipoClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoCliente");
                });

            modelBuilder.Entity("Domain.Entidades.NotasSugerida", b =>
                {
                    b.HasOne("Domain.Entidades.Notas", "Notas")
                        .WithMany("NotasSugeridas")
                        .HasForeignKey("NotasId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Notas");
                });

            modelBuilder.Entity("Domain.Entidades.Cliente", b =>
                {
                    b.Navigation("CaixaEletronica");
                });

            modelBuilder.Entity("Domain.Entidades.Notas", b =>
                {
                    b.Navigation("CaixaEletronicas");

                    b.Navigation("NotasSugeridas");
                });
#pragma warning restore 612, 618
        }
    }
}
